version: '3'

name: sportzone_ecommerce_project
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - mynet
    ports:
      - 5000:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

  web:
    image: stebin13/sportzone_ecommerce
    env_file:
      - .env
    networks:
      - mynet
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

volumes:
  postgres-db:

networks:
  mynet:
    driver: bridge