apiVersion: apps/v1
kind: Deployment
metadata:
  name: sportzone-deployment
  labels:
    app: sportzone-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sportzone-app
  template:
    metadata:
      labels:
        app: sportzone-app
    spec:
      containers:
        - name: ecommerce-app
          image: stebin13/sportzone_ecommerce:1.0
          ports:
            - containerPort: 3000
          env:
            - name: EXPOSE_PORT
              valueFrom:
                configMapKeyRef:
                  name: config-values
                  key: expose-port
            - name: DB_USER
              valueFrom: 
                secretKeyRef:
                  name: postgres-secret
                  key: db-username
            - name: DB_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: postgres-secret
                  key: db-password
            - name: DB_NAME
              valueFrom: 
                secretKeyRef:
                  name: postgres-secret
                  key: db-name
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-values
                  key: db-host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: config-values
                  key: db-port
            - name: JWT_CODE
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: jwt-code
            - name: AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: auth-token
            - name: ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: account-sid
            - name: SERVICE_SID
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: service-sid

---

apiVersion: v1
kind: Service
metadata:
  name: sportzone-service
spec:
  selector:
    app: sportzone-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-config
spec:
  rules:
    - host: sportzone.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sportzone-service
                port:
                  number: 3000