// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/repository/interface/user.go

// Package mockRepo is a generated GoMock package.
package mockRepo

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/stebinsabu13/ecommerce-api/pkg/domain"
	utils "github.com/stebinsabu13/ecommerce-api/pkg/utils"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// AddAddress mocks base method.
func (m *MockUserRepository) AddAddress(arg0 context.Context, arg1 domain.Address) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAddress", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAddress indicates an expected call of AddAddress.
func (mr *MockUserRepositoryMockRecorder) AddAddress(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAddress", reflect.TypeOf((*MockUserRepository)(nil).AddAddress), arg0, arg1)
}

// ChangePassword mocks base method.
func (m *MockUserRepository) ChangePassword(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockUserRepositoryMockRecorder) ChangePassword(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockUserRepository)(nil).ChangePassword), arg0, arg1, arg2)
}

// EditProfile mocks base method.
func (m *MockUserRepository) EditProfile(arg0 context.Context, arg1 utils.EditProfileReq, arg2 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditProfile", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditProfile indicates an expected call of EditProfile.
func (mr *MockUserRepositoryMockRecorder) EditProfile(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditProfile", reflect.TypeOf((*MockUserRepository)(nil).EditProfile), arg0, arg1, arg2)
}

// FindbyEmail mocks base method.
func (m *MockUserRepository) FindbyEmail(ctx context.Context, email string) (utils.ResponseUsers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindbyEmail", ctx, email)
	ret0, _ := ret[0].(utils.ResponseUsers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindbyEmail indicates an expected call of FindbyEmail.
func (mr *MockUserRepositoryMockRecorder) FindbyEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindbyEmail", reflect.TypeOf((*MockUserRepository)(nil).FindbyEmail), ctx, email)
}

// FindbyEmailorMobilenum mocks base method.
func (m *MockUserRepository) FindbyEmailorMobilenum(ctx context.Context, body utils.OtpLogin) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindbyEmailorMobilenum", ctx, body)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindbyEmailorMobilenum indicates an expected call of FindbyEmailorMobilenum.
func (mr *MockUserRepositoryMockRecorder) FindbyEmailorMobilenum(ctx, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindbyEmailorMobilenum", reflect.TypeOf((*MockUserRepository)(nil).FindbyEmailorMobilenum), ctx, body)
}

// FindbyUserID mocks base method.
func (m *MockUserRepository) FindbyUserID(arg0 context.Context, arg1 uint) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindbyUserID", arg0, arg1)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindbyUserID indicates an expected call of FindbyUserID.
func (mr *MockUserRepositoryMockRecorder) FindbyUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindbyUserID", reflect.TypeOf((*MockUserRepository)(nil).FindbyUserID), arg0, arg1)
}

// ListAllCategories mocks base method.
func (m *MockUserRepository) ListAllCategories(ctx context.Context) ([]utils.ResponseCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllCategories", ctx)
	ret0, _ := ret[0].([]utils.ResponseCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllCategories indicates an expected call of ListAllCategories.
func (mr *MockUserRepositoryMockRecorder) ListAllCategories(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllCategories", reflect.TypeOf((*MockUserRepository)(nil).ListAllCategories), ctx)
}

// ShowAddress mocks base method.
func (m *MockUserRepository) ShowAddress(ctx context.Context, id uint) ([]utils.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShowAddress", ctx, id)
	ret0, _ := ret[0].([]utils.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShowAddress indicates an expected call of ShowAddress.
func (mr *MockUserRepositoryMockRecorder) ShowAddress(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowAddress", reflect.TypeOf((*MockUserRepository)(nil).ShowAddress), ctx, id)
}

// ShowDetails mocks base method.
func (m *MockUserRepository) ShowDetails(ctx context.Context, id uint) (utils.ResponseUsers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShowDetails", ctx, id)
	ret0, _ := ret[0].(utils.ResponseUsers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShowDetails indicates an expected call of ShowDetails.
func (mr *MockUserRepositoryMockRecorder) ShowDetails(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowDetails", reflect.TypeOf((*MockUserRepository)(nil).ShowDetails), ctx, id)
}

// SignUpUser mocks base method.
func (m *MockUserRepository) SignUpUser(ctx context.Context, user utils.BodySignUpuser) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignUpUser", ctx, user)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignUpUser indicates an expected call of SignUpUser.
func (mr *MockUserRepositoryMockRecorder) SignUpUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignUpUser", reflect.TypeOf((*MockUserRepository)(nil).SignUpUser), ctx, user)
}

// UpdateVerify mocks base method.
func (m *MockUserRepository) UpdateVerify(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVerify", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVerify indicates an expected call of UpdateVerify.
func (mr *MockUserRepositoryMockRecorder) UpdateVerify(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVerify", reflect.TypeOf((*MockUserRepository)(nil).UpdateVerify), arg0, arg1)
}

// ViewWallet mocks base method.
func (m *MockUserRepository) ViewWallet(arg0 uint) ([]utils.ResWallet, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ViewWallet", arg0)
	ret0, _ := ret[0].([]utils.ResWallet)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ViewWallet indicates an expected call of ViewWallet.
func (mr *MockUserRepositoryMockRecorder) ViewWallet(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewWallet", reflect.TypeOf((*MockUserRepository)(nil).ViewWallet), arg0)
}
