name: Sportzone Project

on:
  push:
    branches:
      - master
  pull:
    branches:
      - master

jobs:
  build:
    name: building and test the project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      #- name: Install dependencies
      #  run: |
      #    go mod tidy
      #    go mod verify
      - name: Build
        run: go build -v ./...
        
      - name: Test
        run: go test -v ./...
        
